name: Renovate Auto Update
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@latest
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_TOKEN }}
