name: Save NPM Test Logs

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  save-test-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: |
          npm update
          npm install

      - name: Run tests and save logs
        run: |
          mkdir -p logs
          npm test > logs/test_logs.txt 2>&1

      - name: Commit and push test logs and updates
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "hostinger-bot"
          git config --global user.email "hostingerbalance@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

          git add logs/test_logs.txt package.json package-lock.json || true

          if ! git diff --cached --quiet; then
            git commit -m "chore: update test logs and dependencies"
          else
            echo "No changes to commit"
          fi

          git stash push -m "temp-stash" || echo "Nothing to stash"

          git pull origin main --rebase || git pull origin main --no-rebase

          if git stash list | grep -q "temp-stash"; then
            git stash pop || echo "Stash pop failed or nothing to pop"
          fi

          git add logs/test_logs.txt package.json package-lock.json || true

          if ! git diff --cached --quiet; then
            git commit -m "chore: update test logs and dependencies"
          fi

          git push origin HEAD || {
            echo "Initial push failed, trying to pull and re-push..."
            git pull --rebase || echo "Rebase failed on retry"
            git push origin HEAD || echo "Push failed after retry"
          }
