name: Save NPM Test Logs
on:
  schedule:
    - cron: "*/5 * * * *"  # Ada tanda kutip yang salah dan kurang bintang
  workflow_dispatch:
jobs:
  save-test-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Menambahkan izin eksplisit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests and save logs
        run: |
          mkdir -p logs
          npm test > logs/test_logs.txt 2>&1
      - name: Commit and push test logs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "hostinger-bot"
          git config --global user.email "hostingerbalance@gmail.com"
          git add logs/test_logs.txt
          git commit -m "chore: update test logs" || echo "No changes to commit"
          # Set remote pakai token
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          # Push ke branch aktif
          git push origin HEAD
