name: Save NPM Test Logs

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  save-test-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: |
          npm update
          npm install

      - name: Run tests and save logs
        run: |
          mkdir -p logs
          npm test > logs/test_logs.txt 2>&1

      - name: Commit and push test logs and updates
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "hostinger-bot"
          git config --global user.email "hostingerbalance@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          
          # Tarik perubahan terbaru dari branch main
          git pull origin main --rebase

          # Tambahkan dan commit perubahan
          git add logs/test_logs.txt package.json package-lock.json
          git commit -m "chore: update test logs and dependencies" || echo "No changes to commit"

          # Push hasil update
          git push origin HEAD
